Algoritmo "funcoesAritmeticas"

Var
   a: Inteiro
   b: Real
   c: Real
   d: Real
   f: Real
   g: Real

Inicio
      a <- Abs(-50)
      Escreval(a)
      
      b <- Exp(9, 5)
      Escreval(b)
      
      c <- RaizQ(81)
      Escreval(c)
      
      d <- Int(RaizQ(90))
      Escreval(d)
      
      f <- GraupRad(90)
      Escreval(f)
      
      g <- Sen(GraupRad(90))
      Escreval(g)

Fimalgoritmo